spring:
  datasource:
    url: jdbc:sqlite:filesql.db
    driver-class-name: org.sqlite.JDBC
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB

mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.jdk14.Jdk14LoggingImpl

server:
  port: 8081

FILE_SAVE_PATH: file_upload/